# Generated by Django 6.0.1 on 2026-01-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploiDuTemps',
        ),
    ]
