# Generated by Django 6.0.1 on 2026-01-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0002_delete_emploidutemps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='matieres',
        ),
        migrations.AddField(
            model_name='professeur',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs', to='emploi_du_temps.matiere'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
