# Generated by Django 5.2.8 on 2026-01-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "emploi_du_temps",
            "0003_remove_professeur_matieres_professeur_matiere_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seance",
            name="jour",
        ),
    ]
